### ISSUE TITLE
Error on 'shield-agent' build

### ISSUE THREAD

**Issue by count0ru** [starkandwayne/shield-docker#1]
```
Step 19/24 : COPY ./mysql ./plugins/bin/mysql
ERROR: Service 'shield-agent' failed to build: lstat mysql: no such file or directory
```

**Comment by jhunt** [comment]
@johnlonganecker is this repo still active, or did we merge this into starkandwayne/shield itself?

**Comment by johnlonganecker** [comment]
Yeah this is merged with https://github.com/starkandwayne/shield in the dev folder, we don't need this repo anymore.

@count0ru can you give https://github.com/starkandwayne/shield/tree/master/dev a whirl and see if you get the same error?

**Comment by count0ru** [comment]
@johnlonganecker https://github.com/starkandwayne/shield/tree/master/dev build fine. Thank you.

**Comment by johnlonganecker** [comment]
Great! Thanks for reporting an issue.
